### ISSUE TITLE
How to generate TF_motif mapping files for a different plant species except arabidopsis, rice and maize?

### ISSUE THREAD

**Issue by e-tomato** [VIB-PSB/MINI-EX#9]
Dear MINI-EX developer,

Thank you for providing this useful tool for plant scRNA-seq analyis. 

I have noticed that there are several folders, including data_ath, data_osa and data_zma in your github repository. Are these files also necessary inputs to perform GRN anlysis? how can I generate them if I'm working with a different plant species, e.g. tomato? I have searched the website and also your MP publication, but it's not very clear to me how these files (motifMapping.out, TF2fam2mo.txt, full_BP_expcur_ext_names.txt) being prepared from which commands, as threre are too many steps and different tools were described in the methods section. 

Thanks in advance,
Best,

**Comment by thdpuydt** [comment]
Dear, 

Apologies for the late reply. 

MINI-EX currently only supports three species: Arabidopsis, rice and maize. This is due to the use of species-specific transcription factor binding site (TFBS) information. In an upcoming release (expected end of the month) **all necessary files for tomato** will be added, as well as an options that will allow **analysis for any species** and only using expression data, by (1) omitting the TFBS analysis (note that this will increase the number of false positive interactions) and/or (2) omitting GO enrichment analysis. 

A detailed description on how to create the motif mapping files for other species will be published towards end of summer (we will keep you posted). In the mean time, a broad description is available in the methods section of the MINI-EX publication: "Motif collection and mapping".

Kind regards,
Thomas

**Comment by e-tomato** [comment]
Thank you very much for you reply, Thomas. 

I would greatly appreciate it if I could obtain a pre-release version of the necessary files, specifically for tomato, as soon as it becomes available. I am eager to try it out with my data, and I will provide you with feedback. I hope this arrangement is acceptable to you.

I am eagerly awaiting your update.

Thank you again.

Best regards,
Guojian  (Email: guojian.hu@inp-toulouse.fr)

**Comment by thdpuydt** [comment]
Hi Guojian,

We are still working on the tomato data. As soon as the files are ready, we will push the release. Of course we would be happy to receive any feedback. 

Best,
Thomas

**Comment by thdpuydt** [comment]
Hi Guojian,

I am pleased to announce that all necessary files to run MINI-EX for tomato have been added to the github page (see folder data_sly). I will close this issue, if you have any remaining questions please feel free to open a new issue.

Good luck with your analysis,
Thomas

**Comment by e-tomato** [comment]
Thank you, Thomas.  I will be conducting a test this week. 

Best,
